services:
  # server:
  #   build:
  #     context: .
  #   environment:
  #     NODE_ENV: production
  #   networks:
  #     - my_network
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: Targaryen
      MONGO_INITDB_ROOT_PASSWORD: WeBuildCoolApps
    networks:
      - my_network

volumes:
  db-data:

networks:
  my_network:
    driver: bridge
